/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TryoutRouteImport } from './routes/tryout'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PremiumRouteImport } from './routes/premium'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as EvaluationRouteImport } from './routes/evaluation'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ComingSoonRouteImport } from './routes/coming-soon'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as BadgesRouteImport } from './routes/badges'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TryoutIdRouteImport } from './routes/tryout.$id'
import { Route as ResultsAttemptIdRouteImport } from './routes/results.$attemptId'
import { Route as ProfileUserIdRouteImport } from './routes/profile.$userId'
import { Route as PollJoinRouteImport } from './routes/poll.join'
import { Route as PollCodeRouteImport } from './routes/poll.$code'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthCompleteProfileRouteImport } from './routes/auth/complete-profile'
import { Route as ResultsAttemptIdReviewRouteImport } from './routes/results.$attemptId.review'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const TryoutRoute = TryoutRouteImport.update({
  id: '/tryout',
  path: '/tryout',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PremiumRoute = PremiumRouteImport.update({
  id: '/premium',
  path: '/premium',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const EvaluationRoute = EvaluationRouteImport.update({
  id: '/evaluation',
  path: '/evaluation',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ComingSoonRoute = ComingSoonRouteImport.update({
  id: '/coming-soon',
  path: '/coming-soon',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const BadgesRoute = BadgesRouteImport.update({
  id: '/badges',
  path: '/badges',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TryoutIdRoute = TryoutIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => TryoutRoute,
} as any)
const ResultsAttemptIdRoute = ResultsAttemptIdRouteImport.update({
  id: '/results/$attemptId',
  path: '/results/$attemptId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileUserIdRoute = ProfileUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => ProfileRoute,
} as any)
const PollJoinRoute = PollJoinRouteImport.update({
  id: '/poll/join',
  path: '/poll/join',
  getParentRoute: () => rootRouteImport,
} as any)
const PollCodeRoute = PollCodeRouteImport.update({
  id: '/poll/$code',
  path: '/poll/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCompleteProfileRoute = AuthCompleteProfileRouteImport.update({
  id: '/auth/complete-profile',
  path: '/auth/complete-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsAttemptIdReviewRoute = ResultsAttemptIdReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => ResultsAttemptIdRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/badges': typeof BadgesRoute
  '/checkout': typeof CheckoutRoute
  '/coming-soon': typeof ComingSoonRoute
  '/dashboard': typeof DashboardRoute
  '/evaluation': typeof EvaluationRoute
  '/leaderboard': typeof LeaderboardRoute
  '/premium': typeof PremiumRoute
  '/profile': typeof ProfileRouteWithChildren
  '/progress': typeof ProgressRoute
  '/tryout': typeof TryoutRouteWithChildren
  '/auth/complete-profile': typeof AuthCompleteProfileRoute
  '/auth/login': typeof AuthLoginRoute
  '/poll/$code': typeof PollCodeRoute
  '/poll/join': typeof PollJoinRoute
  '/profile/$userId': typeof ProfileUserIdRoute
  '/results/$attemptId': typeof ResultsAttemptIdRouteWithChildren
  '/tryout/$id': typeof TryoutIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/results/$attemptId/review': typeof ResultsAttemptIdReviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/badges': typeof BadgesRoute
  '/checkout': typeof CheckoutRoute
  '/coming-soon': typeof ComingSoonRoute
  '/dashboard': typeof DashboardRoute
  '/evaluation': typeof EvaluationRoute
  '/leaderboard': typeof LeaderboardRoute
  '/premium': typeof PremiumRoute
  '/profile': typeof ProfileRouteWithChildren
  '/progress': typeof ProgressRoute
  '/tryout': typeof TryoutRouteWithChildren
  '/auth/complete-profile': typeof AuthCompleteProfileRoute
  '/auth/login': typeof AuthLoginRoute
  '/poll/$code': typeof PollCodeRoute
  '/poll/join': typeof PollJoinRoute
  '/profile/$userId': typeof ProfileUserIdRoute
  '/results/$attemptId': typeof ResultsAttemptIdRouteWithChildren
  '/tryout/$id': typeof TryoutIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/results/$attemptId/review': typeof ResultsAttemptIdReviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/badges': typeof BadgesRoute
  '/checkout': typeof CheckoutRoute
  '/coming-soon': typeof ComingSoonRoute
  '/dashboard': typeof DashboardRoute
  '/evaluation': typeof EvaluationRoute
  '/leaderboard': typeof LeaderboardRoute
  '/premium': typeof PremiumRoute
  '/profile': typeof ProfileRouteWithChildren
  '/progress': typeof ProgressRoute
  '/tryout': typeof TryoutRouteWithChildren
  '/auth/complete-profile': typeof AuthCompleteProfileRoute
  '/auth/login': typeof AuthLoginRoute
  '/poll/$code': typeof PollCodeRoute
  '/poll/join': typeof PollJoinRoute
  '/profile/$userId': typeof ProfileUserIdRoute
  '/results/$attemptId': typeof ResultsAttemptIdRouteWithChildren
  '/tryout/$id': typeof TryoutIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/results/$attemptId/review': typeof ResultsAttemptIdReviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/badges'
    | '/checkout'
    | '/coming-soon'
    | '/dashboard'
    | '/evaluation'
    | '/leaderboard'
    | '/premium'
    | '/profile'
    | '/progress'
    | '/tryout'
    | '/auth/complete-profile'
    | '/auth/login'
    | '/poll/$code'
    | '/poll/join'
    | '/profile/$userId'
    | '/results/$attemptId'
    | '/tryout/$id'
    | '/api/auth/$'
    | '/results/$attemptId/review'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/badges'
    | '/checkout'
    | '/coming-soon'
    | '/dashboard'
    | '/evaluation'
    | '/leaderboard'
    | '/premium'
    | '/profile'
    | '/progress'
    | '/tryout'
    | '/auth/complete-profile'
    | '/auth/login'
    | '/poll/$code'
    | '/poll/join'
    | '/profile/$userId'
    | '/results/$attemptId'
    | '/tryout/$id'
    | '/api/auth/$'
    | '/results/$attemptId/review'
  id:
    | '__root__'
    | '/'
    | '/badges'
    | '/checkout'
    | '/coming-soon'
    | '/dashboard'
    | '/evaluation'
    | '/leaderboard'
    | '/premium'
    | '/profile'
    | '/progress'
    | '/tryout'
    | '/auth/complete-profile'
    | '/auth/login'
    | '/poll/$code'
    | '/poll/join'
    | '/profile/$userId'
    | '/results/$attemptId'
    | '/tryout/$id'
    | '/api/auth/$'
    | '/results/$attemptId/review'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BadgesRoute: typeof BadgesRoute
  CheckoutRoute: typeof CheckoutRoute
  ComingSoonRoute: typeof ComingSoonRoute
  DashboardRoute: typeof DashboardRoute
  EvaluationRoute: typeof EvaluationRoute
  LeaderboardRoute: typeof LeaderboardRoute
  PremiumRoute: typeof PremiumRoute
  ProfileRoute: typeof ProfileRouteWithChildren
  ProgressRoute: typeof ProgressRoute
  TryoutRoute: typeof TryoutRouteWithChildren
  AuthCompleteProfileRoute: typeof AuthCompleteProfileRoute
  AuthLoginRoute: typeof AuthLoginRoute
  PollCodeRoute: typeof PollCodeRoute
  PollJoinRoute: typeof PollJoinRoute
  ResultsAttemptIdRoute: typeof ResultsAttemptIdRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tryout': {
      id: '/tryout'
      path: '/tryout'
      fullPath: '/tryout'
      preLoaderRoute: typeof TryoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/premium': {
      id: '/premium'
      path: '/premium'
      fullPath: '/premium'
      preLoaderRoute: typeof PremiumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evaluation': {
      id: '/evaluation'
      path: '/evaluation'
      fullPath: '/evaluation'
      preLoaderRoute: typeof EvaluationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coming-soon': {
      id: '/coming-soon'
      path: '/coming-soon'
      fullPath: '/coming-soon'
      preLoaderRoute: typeof ComingSoonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/badges': {
      id: '/badges'
      path: '/badges'
      fullPath: '/badges'
      preLoaderRoute: typeof BadgesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tryout/$id': {
      id: '/tryout/$id'
      path: '/$id'
      fullPath: '/tryout/$id'
      preLoaderRoute: typeof TryoutIdRouteImport
      parentRoute: typeof TryoutRoute
    }
    '/results/$attemptId': {
      id: '/results/$attemptId'
      path: '/results/$attemptId'
      fullPath: '/results/$attemptId'
      preLoaderRoute: typeof ResultsAttemptIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$userId': {
      id: '/profile/$userId'
      path: '/$userId'
      fullPath: '/profile/$userId'
      preLoaderRoute: typeof ProfileUserIdRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/poll/join': {
      id: '/poll/join'
      path: '/poll/join'
      fullPath: '/poll/join'
      preLoaderRoute: typeof PollJoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/poll/$code': {
      id: '/poll/$code'
      path: '/poll/$code'
      fullPath: '/poll/$code'
      preLoaderRoute: typeof PollCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/complete-profile': {
      id: '/auth/complete-profile'
      path: '/auth/complete-profile'
      fullPath: '/auth/complete-profile'
      preLoaderRoute: typeof AuthCompleteProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results/$attemptId/review': {
      id: '/results/$attemptId/review'
      path: '/review'
      fullPath: '/results/$attemptId/review'
      preLoaderRoute: typeof ResultsAttemptIdReviewRouteImport
      parentRoute: typeof ResultsAttemptIdRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ProfileRouteChildren {
  ProfileUserIdRoute: typeof ProfileUserIdRoute
}

const ProfileRouteChildren: ProfileRouteChildren = {
  ProfileUserIdRoute: ProfileUserIdRoute,
}

const ProfileRouteWithChildren =
  ProfileRoute._addFileChildren(ProfileRouteChildren)

interface TryoutRouteChildren {
  TryoutIdRoute: typeof TryoutIdRoute
}

const TryoutRouteChildren: TryoutRouteChildren = {
  TryoutIdRoute: TryoutIdRoute,
}

const TryoutRouteWithChildren =
  TryoutRoute._addFileChildren(TryoutRouteChildren)

interface ResultsAttemptIdRouteChildren {
  ResultsAttemptIdReviewRoute: typeof ResultsAttemptIdReviewRoute
}

const ResultsAttemptIdRouteChildren: ResultsAttemptIdRouteChildren = {
  ResultsAttemptIdReviewRoute: ResultsAttemptIdReviewRoute,
}

const ResultsAttemptIdRouteWithChildren =
  ResultsAttemptIdRoute._addFileChildren(ResultsAttemptIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BadgesRoute: BadgesRoute,
  CheckoutRoute: CheckoutRoute,
  ComingSoonRoute: ComingSoonRoute,
  DashboardRoute: DashboardRoute,
  EvaluationRoute: EvaluationRoute,
  LeaderboardRoute: LeaderboardRoute,
  PremiumRoute: PremiumRoute,
  ProfileRoute: ProfileRouteWithChildren,
  ProgressRoute: ProgressRoute,
  TryoutRoute: TryoutRouteWithChildren,
  AuthCompleteProfileRoute: AuthCompleteProfileRoute,
  AuthLoginRoute: AuthLoginRoute,
  PollCodeRoute: PollCodeRoute,
  PollJoinRoute: PollJoinRoute,
  ResultsAttemptIdRoute: ResultsAttemptIdRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
