/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TryoutRouteImport } from './routes/tryout'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PremiumRouteImport } from './routes/premium'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as EvaluationRouteImport } from './routes/evaluation'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ComingSoonRouteImport } from './routes/coming-soon'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as BadgesRouteImport } from './routes/badges'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TryoutIdRouteImport } from './routes/tryout.$id'
import { Route as ResultsAttemptIdRouteImport } from './routes/results.$attemptId'
import { Route as ProfileUserIdRouteImport } from './routes/profile.$userId'
import { Route as PollJoinRouteImport } from './routes/poll.join'
import { Route as PollCodeRouteImport } from './routes/poll.$code'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthCompleteProfileRouteImport } from './routes/auth/complete-profile'
import { Route as ApiHealthzRouteImport } from './routes/api/healthz'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminTryoutsRouteImport } from './routes/admin/tryouts'
import { Route as AdminReportsRouteImport } from './routes/admin/reports'
import { Route as AdminQuestionsRouteImport } from './routes/admin/questions'
import { Route as AdminPollsRouteImport } from './routes/admin/polls'
import { Route as AdminMonitoringRouteImport } from './routes/admin/monitoring'
import { Route as AdminMateriRouteImport } from './routes/admin/materi'
import { Route as AdminInsightsRouteImport } from './routes/admin/insights'
import { Route as ResultsAttemptIdReviewRouteImport } from './routes/results.$attemptId.review'
import { Route as ApiPollsEventsRouteImport } from './routes/api/polls/events'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AdminTryoutsIdRouteImport } from './routes/admin/tryouts.$id'
import { Route as AdminPollsPresentationRouteImport } from './routes/admin/polls_.presentation'

const TryoutRoute = TryoutRouteImport.update({
  id: '/tryout',
  path: '/tryout',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PremiumRoute = PremiumRouteImport.update({
  id: '/premium',
  path: '/premium',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const EvaluationRoute = EvaluationRouteImport.update({
  id: '/evaluation',
  path: '/evaluation',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ComingSoonRoute = ComingSoonRouteImport.update({
  id: '/coming-soon',
  path: '/coming-soon',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const BadgesRoute = BadgesRouteImport.update({
  id: '/badges',
  path: '/badges',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TryoutIdRoute = TryoutIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => TryoutRoute,
} as any)
const ResultsAttemptIdRoute = ResultsAttemptIdRouteImport.update({
  id: '/results/$attemptId',
  path: '/results/$attemptId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileUserIdRoute = ProfileUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => ProfileRoute,
} as any)
const PollJoinRoute = PollJoinRouteImport.update({
  id: '/poll/join',
  path: '/poll/join',
  getParentRoute: () => rootRouteImport,
} as any)
const PollCodeRoute = PollCodeRouteImport.update({
  id: '/poll/$code',
  path: '/poll/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCompleteProfileRoute = AuthCompleteProfileRouteImport.update({
  id: '/auth/complete-profile',
  path: '/auth/complete-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthzRoute = ApiHealthzRouteImport.update({
  id: '/api/healthz',
  path: '/api/healthz',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTryoutsRoute = AdminTryoutsRouteImport.update({
  id: '/tryouts',
  path: '/tryouts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminQuestionsRoute = AdminQuestionsRouteImport.update({
  id: '/questions',
  path: '/questions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPollsRoute = AdminPollsRouteImport.update({
  id: '/polls',
  path: '/polls',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMonitoringRoute = AdminMonitoringRouteImport.update({
  id: '/monitoring',
  path: '/monitoring',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMateriRoute = AdminMateriRouteImport.update({
  id: '/materi',
  path: '/materi',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInsightsRoute = AdminInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => AdminRoute,
} as any)
const ResultsAttemptIdReviewRoute = ResultsAttemptIdReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => ResultsAttemptIdRoute,
} as any)
const ApiPollsEventsRoute = ApiPollsEventsRouteImport.update({
  id: '/api/polls/events',
  path: '/api/polls/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTryoutsIdRoute = AdminTryoutsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminTryoutsRoute,
} as any)
const AdminPollsPresentationRoute = AdminPollsPresentationRouteImport.update({
  id: '/polls_/presentation',
  path: '/polls/presentation',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/badges': typeof BadgesRoute
  '/checkout': typeof CheckoutRoute
  '/coming-soon': typeof ComingSoonRoute
  '/dashboard': typeof DashboardRoute
  '/evaluation': typeof EvaluationRoute
  '/leaderboard': typeof LeaderboardRoute
  '/premium': typeof PremiumRoute
  '/profile': typeof ProfileRouteWithChildren
  '/progress': typeof ProgressRoute
  '/tryout': typeof TryoutRouteWithChildren
  '/admin/insights': typeof AdminInsightsRoute
  '/admin/materi': typeof AdminMateriRoute
  '/admin/monitoring': typeof AdminMonitoringRoute
  '/admin/polls': typeof AdminPollsRoute
  '/admin/questions': typeof AdminQuestionsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/tryouts': typeof AdminTryoutsRouteWithChildren
  '/admin/users': typeof AdminUsersRoute
  '/api/healthz': typeof ApiHealthzRoute
  '/auth/complete-profile': typeof AuthCompleteProfileRoute
  '/auth/login': typeof AuthLoginRoute
  '/poll/$code': typeof PollCodeRoute
  '/poll/join': typeof PollJoinRoute
  '/profile/$userId': typeof ProfileUserIdRoute
  '/results/$attemptId': typeof ResultsAttemptIdRouteWithChildren
  '/tryout/$id': typeof TryoutIdRoute
  '/admin/polls/presentation': typeof AdminPollsPresentationRoute
  '/admin/tryouts/$id': typeof AdminTryoutsIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/polls/events': typeof ApiPollsEventsRoute
  '/results/$attemptId/review': typeof ResultsAttemptIdReviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/badges': typeof BadgesRoute
  '/checkout': typeof CheckoutRoute
  '/coming-soon': typeof ComingSoonRoute
  '/dashboard': typeof DashboardRoute
  '/evaluation': typeof EvaluationRoute
  '/leaderboard': typeof LeaderboardRoute
  '/premium': typeof PremiumRoute
  '/profile': typeof ProfileRouteWithChildren
  '/progress': typeof ProgressRoute
  '/tryout': typeof TryoutRouteWithChildren
  '/admin/insights': typeof AdminInsightsRoute
  '/admin/materi': typeof AdminMateriRoute
  '/admin/monitoring': typeof AdminMonitoringRoute
  '/admin/polls': typeof AdminPollsRoute
  '/admin/questions': typeof AdminQuestionsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/tryouts': typeof AdminTryoutsRouteWithChildren
  '/admin/users': typeof AdminUsersRoute
  '/api/healthz': typeof ApiHealthzRoute
  '/auth/complete-profile': typeof AuthCompleteProfileRoute
  '/auth/login': typeof AuthLoginRoute
  '/poll/$code': typeof PollCodeRoute
  '/poll/join': typeof PollJoinRoute
  '/profile/$userId': typeof ProfileUserIdRoute
  '/results/$attemptId': typeof ResultsAttemptIdRouteWithChildren
  '/tryout/$id': typeof TryoutIdRoute
  '/admin/polls/presentation': typeof AdminPollsPresentationRoute
  '/admin/tryouts/$id': typeof AdminTryoutsIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/polls/events': typeof ApiPollsEventsRoute
  '/results/$attemptId/review': typeof ResultsAttemptIdReviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/badges': typeof BadgesRoute
  '/checkout': typeof CheckoutRoute
  '/coming-soon': typeof ComingSoonRoute
  '/dashboard': typeof DashboardRoute
  '/evaluation': typeof EvaluationRoute
  '/leaderboard': typeof LeaderboardRoute
  '/premium': typeof PremiumRoute
  '/profile': typeof ProfileRouteWithChildren
  '/progress': typeof ProgressRoute
  '/tryout': typeof TryoutRouteWithChildren
  '/admin/insights': typeof AdminInsightsRoute
  '/admin/materi': typeof AdminMateriRoute
  '/admin/monitoring': typeof AdminMonitoringRoute
  '/admin/polls': typeof AdminPollsRoute
  '/admin/questions': typeof AdminQuestionsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/tryouts': typeof AdminTryoutsRouteWithChildren
  '/admin/users': typeof AdminUsersRoute
  '/api/healthz': typeof ApiHealthzRoute
  '/auth/complete-profile': typeof AuthCompleteProfileRoute
  '/auth/login': typeof AuthLoginRoute
  '/poll/$code': typeof PollCodeRoute
  '/poll/join': typeof PollJoinRoute
  '/profile/$userId': typeof ProfileUserIdRoute
  '/results/$attemptId': typeof ResultsAttemptIdRouteWithChildren
  '/tryout/$id': typeof TryoutIdRoute
  '/admin/polls_/presentation': typeof AdminPollsPresentationRoute
  '/admin/tryouts/$id': typeof AdminTryoutsIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/polls/events': typeof ApiPollsEventsRoute
  '/results/$attemptId/review': typeof ResultsAttemptIdReviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/badges'
    | '/checkout'
    | '/coming-soon'
    | '/dashboard'
    | '/evaluation'
    | '/leaderboard'
    | '/premium'
    | '/profile'
    | '/progress'
    | '/tryout'
    | '/admin/insights'
    | '/admin/materi'
    | '/admin/monitoring'
    | '/admin/polls'
    | '/admin/questions'
    | '/admin/reports'
    | '/admin/tryouts'
    | '/admin/users'
    | '/api/healthz'
    | '/auth/complete-profile'
    | '/auth/login'
    | '/poll/$code'
    | '/poll/join'
    | '/profile/$userId'
    | '/results/$attemptId'
    | '/tryout/$id'
    | '/admin/polls/presentation'
    | '/admin/tryouts/$id'
    | '/api/auth/$'
    | '/api/polls/events'
    | '/results/$attemptId/review'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/badges'
    | '/checkout'
    | '/coming-soon'
    | '/dashboard'
    | '/evaluation'
    | '/leaderboard'
    | '/premium'
    | '/profile'
    | '/progress'
    | '/tryout'
    | '/admin/insights'
    | '/admin/materi'
    | '/admin/monitoring'
    | '/admin/polls'
    | '/admin/questions'
    | '/admin/reports'
    | '/admin/tryouts'
    | '/admin/users'
    | '/api/healthz'
    | '/auth/complete-profile'
    | '/auth/login'
    | '/poll/$code'
    | '/poll/join'
    | '/profile/$userId'
    | '/results/$attemptId'
    | '/tryout/$id'
    | '/admin/polls/presentation'
    | '/admin/tryouts/$id'
    | '/api/auth/$'
    | '/api/polls/events'
    | '/results/$attemptId/review'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/badges'
    | '/checkout'
    | '/coming-soon'
    | '/dashboard'
    | '/evaluation'
    | '/leaderboard'
    | '/premium'
    | '/profile'
    | '/progress'
    | '/tryout'
    | '/admin/insights'
    | '/admin/materi'
    | '/admin/monitoring'
    | '/admin/polls'
    | '/admin/questions'
    | '/admin/reports'
    | '/admin/tryouts'
    | '/admin/users'
    | '/api/healthz'
    | '/auth/complete-profile'
    | '/auth/login'
    | '/poll/$code'
    | '/poll/join'
    | '/profile/$userId'
    | '/results/$attemptId'
    | '/tryout/$id'
    | '/admin/polls_/presentation'
    | '/admin/tryouts/$id'
    | '/api/auth/$'
    | '/api/polls/events'
    | '/results/$attemptId/review'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  BadgesRoute: typeof BadgesRoute
  CheckoutRoute: typeof CheckoutRoute
  ComingSoonRoute: typeof ComingSoonRoute
  DashboardRoute: typeof DashboardRoute
  EvaluationRoute: typeof EvaluationRoute
  LeaderboardRoute: typeof LeaderboardRoute
  PremiumRoute: typeof PremiumRoute
  ProfileRoute: typeof ProfileRouteWithChildren
  ProgressRoute: typeof ProgressRoute
  TryoutRoute: typeof TryoutRouteWithChildren
  ApiHealthzRoute: typeof ApiHealthzRoute
  AuthCompleteProfileRoute: typeof AuthCompleteProfileRoute
  AuthLoginRoute: typeof AuthLoginRoute
  PollCodeRoute: typeof PollCodeRoute
  PollJoinRoute: typeof PollJoinRoute
  ResultsAttemptIdRoute: typeof ResultsAttemptIdRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiPollsEventsRoute: typeof ApiPollsEventsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tryout': {
      id: '/tryout'
      path: '/tryout'
      fullPath: '/tryout'
      preLoaderRoute: typeof TryoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/premium': {
      id: '/premium'
      path: '/premium'
      fullPath: '/premium'
      preLoaderRoute: typeof PremiumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evaluation': {
      id: '/evaluation'
      path: '/evaluation'
      fullPath: '/evaluation'
      preLoaderRoute: typeof EvaluationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coming-soon': {
      id: '/coming-soon'
      path: '/coming-soon'
      fullPath: '/coming-soon'
      preLoaderRoute: typeof ComingSoonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/badges': {
      id: '/badges'
      path: '/badges'
      fullPath: '/badges'
      preLoaderRoute: typeof BadgesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tryout/$id': {
      id: '/tryout/$id'
      path: '/$id'
      fullPath: '/tryout/$id'
      preLoaderRoute: typeof TryoutIdRouteImport
      parentRoute: typeof TryoutRoute
    }
    '/results/$attemptId': {
      id: '/results/$attemptId'
      path: '/results/$attemptId'
      fullPath: '/results/$attemptId'
      preLoaderRoute: typeof ResultsAttemptIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$userId': {
      id: '/profile/$userId'
      path: '/$userId'
      fullPath: '/profile/$userId'
      preLoaderRoute: typeof ProfileUserIdRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/poll/join': {
      id: '/poll/join'
      path: '/poll/join'
      fullPath: '/poll/join'
      preLoaderRoute: typeof PollJoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/poll/$code': {
      id: '/poll/$code'
      path: '/poll/$code'
      fullPath: '/poll/$code'
      preLoaderRoute: typeof PollCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/complete-profile': {
      id: '/auth/complete-profile'
      path: '/auth/complete-profile'
      fullPath: '/auth/complete-profile'
      preLoaderRoute: typeof AuthCompleteProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/healthz': {
      id: '/api/healthz'
      path: '/api/healthz'
      fullPath: '/api/healthz'
      preLoaderRoute: typeof ApiHealthzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tryouts': {
      id: '/admin/tryouts'
      path: '/tryouts'
      fullPath: '/admin/tryouts'
      preLoaderRoute: typeof AdminTryoutsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/questions': {
      id: '/admin/questions'
      path: '/questions'
      fullPath: '/admin/questions'
      preLoaderRoute: typeof AdminQuestionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/polls': {
      id: '/admin/polls'
      path: '/polls'
      fullPath: '/admin/polls'
      preLoaderRoute: typeof AdminPollsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/monitoring': {
      id: '/admin/monitoring'
      path: '/monitoring'
      fullPath: '/admin/monitoring'
      preLoaderRoute: typeof AdminMonitoringRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/materi': {
      id: '/admin/materi'
      path: '/materi'
      fullPath: '/admin/materi'
      preLoaderRoute: typeof AdminMateriRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/insights': {
      id: '/admin/insights'
      path: '/insights'
      fullPath: '/admin/insights'
      preLoaderRoute: typeof AdminInsightsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/results/$attemptId/review': {
      id: '/results/$attemptId/review'
      path: '/review'
      fullPath: '/results/$attemptId/review'
      preLoaderRoute: typeof ResultsAttemptIdReviewRouteImport
      parentRoute: typeof ResultsAttemptIdRoute
    }
    '/api/polls/events': {
      id: '/api/polls/events'
      path: '/api/polls/events'
      fullPath: '/api/polls/events'
      preLoaderRoute: typeof ApiPollsEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/tryouts/$id': {
      id: '/admin/tryouts/$id'
      path: '/$id'
      fullPath: '/admin/tryouts/$id'
      preLoaderRoute: typeof AdminTryoutsIdRouteImport
      parentRoute: typeof AdminTryoutsRoute
    }
    '/admin/polls_/presentation': {
      id: '/admin/polls_/presentation'
      path: '/polls/presentation'
      fullPath: '/admin/polls/presentation'
      preLoaderRoute: typeof AdminPollsPresentationRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminTryoutsRouteChildren {
  AdminTryoutsIdRoute: typeof AdminTryoutsIdRoute
}

const AdminTryoutsRouteChildren: AdminTryoutsRouteChildren = {
  AdminTryoutsIdRoute: AdminTryoutsIdRoute,
}

const AdminTryoutsRouteWithChildren = AdminTryoutsRoute._addFileChildren(
  AdminTryoutsRouteChildren,
)

interface AdminRouteChildren {
  AdminInsightsRoute: typeof AdminInsightsRoute
  AdminMateriRoute: typeof AdminMateriRoute
  AdminMonitoringRoute: typeof AdminMonitoringRoute
  AdminPollsRoute: typeof AdminPollsRoute
  AdminQuestionsRoute: typeof AdminQuestionsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminTryoutsRoute: typeof AdminTryoutsRouteWithChildren
  AdminUsersRoute: typeof AdminUsersRoute
  AdminPollsPresentationRoute: typeof AdminPollsPresentationRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminInsightsRoute: AdminInsightsRoute,
  AdminMateriRoute: AdminMateriRoute,
  AdminMonitoringRoute: AdminMonitoringRoute,
  AdminPollsRoute: AdminPollsRoute,
  AdminQuestionsRoute: AdminQuestionsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminTryoutsRoute: AdminTryoutsRouteWithChildren,
  AdminUsersRoute: AdminUsersRoute,
  AdminPollsPresentationRoute: AdminPollsPresentationRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ProfileRouteChildren {
  ProfileUserIdRoute: typeof ProfileUserIdRoute
}

const ProfileRouteChildren: ProfileRouteChildren = {
  ProfileUserIdRoute: ProfileUserIdRoute,
}

const ProfileRouteWithChildren =
  ProfileRoute._addFileChildren(ProfileRouteChildren)

interface TryoutRouteChildren {
  TryoutIdRoute: typeof TryoutIdRoute
}

const TryoutRouteChildren: TryoutRouteChildren = {
  TryoutIdRoute: TryoutIdRoute,
}

const TryoutRouteWithChildren =
  TryoutRoute._addFileChildren(TryoutRouteChildren)

interface ResultsAttemptIdRouteChildren {
  ResultsAttemptIdReviewRoute: typeof ResultsAttemptIdReviewRoute
}

const ResultsAttemptIdRouteChildren: ResultsAttemptIdRouteChildren = {
  ResultsAttemptIdReviewRoute: ResultsAttemptIdReviewRoute,
}

const ResultsAttemptIdRouteWithChildren =
  ResultsAttemptIdRoute._addFileChildren(ResultsAttemptIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  BadgesRoute: BadgesRoute,
  CheckoutRoute: CheckoutRoute,
  ComingSoonRoute: ComingSoonRoute,
  DashboardRoute: DashboardRoute,
  EvaluationRoute: EvaluationRoute,
  LeaderboardRoute: LeaderboardRoute,
  PremiumRoute: PremiumRoute,
  ProfileRoute: ProfileRouteWithChildren,
  ProgressRoute: ProgressRoute,
  TryoutRoute: TryoutRouteWithChildren,
  ApiHealthzRoute: ApiHealthzRoute,
  AuthCompleteProfileRoute: AuthCompleteProfileRoute,
  AuthLoginRoute: AuthLoginRoute,
  PollCodeRoute: PollCodeRoute,
  PollJoinRoute: PollJoinRoute,
  ResultsAttemptIdRoute: ResultsAttemptIdRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiPollsEventsRoute: ApiPollsEventsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
